name: acc-env
channels:
  - conda-forge
dependencies:
  - c-compiler
  - cxx-compiler
  - fortran-compiler
  - boost-cpp
  - gsl
  - eigen
  - fftw
  - cfitsio
  - swig
  - python=3.12
  - jupyterlab
  - numpy
  - matplotlib
  - sympy
  - scipy
  - tqdm
  - healpy
  - colorama
  - astropy
  - sphinx
  - ipykernel
  - pandas
  - scikit-learn
  - camb
  - seaborn
  - scikit-learn
  
